export const serviceDictionary: { [key: string]: string } = {
    basicneedsservice: "Basic Needs Service",
    casemanagementservice: "Case Management Service",
    benefitsassistanceservice: "Benefits Assistance Service",
    permanenthousingguidanceservice: "Permanent Housing Guidance Service",
    financialsupportservice: "Financial Support Service",
    moveinandrentalassistanceservice: "Move-In and Rental Assistance Service",
    travelservice: "Travel Service",
    familyservicesservice: "Family Services Service",
    harmandcrisisinterventionservice: "Harm and Crisis Intervention Service",
    foodandwaterservice: "Food and Water Service",
    mentalhealthsupportservice: "Mental Health Support Service",
    substanceabusesupportservice: "Substance Abuse Support Service",
    healthcareassistanceservice: "Healthcare Assistance Service",
    employmentsupportservice: "Employment Support Service",
    educationsupportservice: "Education Support Service",
    temporaryhousingguidanceservice: "Temporary Housing Guidance Service",
    travelassistanceservice: "Travel Assistance Service",
    hygienesuppliesservice: "Hygiene Supplies Service",
    documentsupportservice: "Document Support Service",
    petsupportservice: "Pet Support Service",
    lifeskillsservice: "Life Skills Service",
    communitysupportservice: "Community Support Service",
    veteranservicesservice: "Veteran Services Service",
    legalsupportservice: "Legal Support Service",
    covidsupportservice: "COVID Support Service",
    disabilitysupportservice: "Disability Support Service",
    creditsupportservice: "Credit Support Service",
    housingsearchservice: "Housing Search Service",
    sheltersupportservice: "Shelter Support Service",
    referrallinkageinformationservice: "Referral Linkage Information Service"
};

export const serviceDescriptions: { [key: string]: string } = {
    basicneedsservice: "Support providing daily necessities such as clothing, bedding, phone services, mail handling, and material goods, often offered in a shelter setting to address participants' immediate needs.",
    casemanagementservice: "Continuous interaction and support from a case manager to ensure participants' needs are addressed, even when no specific service is provided.",
    benefitsassistanceservice: "Assistance with navigating, applying for, and securing benefits to help participants access necessary resources for stability.",
    permanenthousingguidanceservice: "Support with housing navigation and placement plans, helping participants identify and secure permanent housing solutions based on their needs and circumstances.",
    financialsupportservice: "Help covering fees, arrears, deposits, and other financial needs to provide stability and address participants' urgent monetary concerns.",
    moveinandrentalassistanceservice: "Aid with moving costs, essential furnishings, utility fees, security deposits, and other expenses related to establishing or maintaining housing.",
    travelassistanceservice: "Support for transportation needs, including bus passes, ride scheduling, vehicle repair fees, DMV vouchers, and reunification travel.",
    familyservicesservice: "Services to assist with childcare, parental support, and family reunification for participants facing challenges related to family dynamics.",
    harmandcrisisinterventionservice: "Emergency response and crisis intervention services involving law enforcement or ambulatory support to address immediate participant safety.",
    foodandwaterservice: "Provision of food, meal cards, grocery cards, or water to address participants' basic nutritional needs.",
    mentalhealthsupportservice: "Referrals or access to mental health practitioners, evaluations, and counseling to address behavioral and psychological needs.",
    substanceabusesupportservice: "Assistance with drug or alcohol treatment, counseling, Narcan/naloxone provision, and needle exchange programs.",
    healthcareassistanceservice: "Support related to participants' physical health, including evaluations, pharmaceutical assistance, and healthcare referrals.",
    employmentsupportservice: "Assistance with employment development, resume building, vocational counseling, interview preparation, and job opportunity linkages.",
    educationsupportservice: "Support for accessing educational resources and supplies, as well as guidance on furthering education and career prospects.",
    temporaryhousingguidanceservice: "Support in finding temporary housing options through formal requests and placements to ensure participants have safe interim accommodations.",
    hygienesuppliesservice: "Provision of hygiene supplies to maintain participants' personal cleanliness and well-being.",
    documentsupportservice: "Assistance in obtaining critical documents such as birth certificates, driver’s licenses, and social security cards.",
    petsupportservice: "Services supporting participants with pets, ensuring the well-being of both the individual and their animal companion.",
    lifeskillsservice: "Guidance and training in essential life skills to help participants achieve greater independence and stability.",
    communitysupportservice: "Opportunities for participants to engage in group therapy, support groups, or community events fostering interaction and peer support.",
    veteranservicesservice: "Specialized support addressing the unique needs of veterans, including benefits and reintegration services.",
    legalsupportservice: "Assistance with legal aid, legal fees, and documentation to help participants address legal challenges.",
    covidsupportservice: "Support for participants affected by or at risk of COVID-19, including PPE distribution, testing, and vaccination services.",
    disabilitysupportservice: "Services designed to assist participants with disabilities, ensuring access to appropriate resources and accommodations.",
    creditsupportservice: "Support with financial literacy, credit repair, credit counseling, and credit score management to improve participants' financial stability.",
    housingsearchservice: "Guidance in searching for and identifying suitable housing options for participants in need of stable accommodations.",
    sheltersupportservice: "Referrals and placements into shelters, providing participants with safe and temporary living arrangements.",
    referrallinkageinformationservice: "Supplemental support through referrals, resource linkages, and information sharing to help participants access additional opportunities and services."
};
